name: MLOs CICD pipeline

on:
  push:
    branches:
      - main
  jobs:
    build-train-test-deploy:
      runs-on: ubuntu-latest

    steps:
     - name: checkout repository
       uses: actions?setup - python@v4
       with:
       python-version: '3.9'

    - name: Install dependencies
      run:
       python - m pip install - upgrad pip
       pip install -r requirments.txt

    - name: run churn analysis
      run: python curn_analysis.py
